# Generated by Django 3.0.7 on 2020-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date2',
            field=models.DateField(default=0),
        ),
    ]
