# Generated by Django 3.0.7 on 2020-07-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date2',
        ),
    ]
