# Generated by Django 3.0.7 on 2020-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='personalportfolio'),
        ),
    ]
